In [2]:
import numpy as np

In [3]:
def multpol(a,b):  #multiplicacion de polinomios binarios
    gr1= len(a)-1  #recordar que los polinomios están ordenado de mayor a menor
    gr2= len(b)-1  #al reves que la ordenación del array
    c=np.zeros(gr1+gr2+1)
    for k in range(0,gr1+gr2+1):
        for i in range (0,gr1+1):
            for j in range(0,gr2+1):
                if i+j == k : 
                    c[gr1+gr2-k] += a[gr1 -i] * b[gr2-j]
                    break
        c[gr1+gr2-k] =  c[gr1+gr2-k] %2           
    return list(c) #se obtiene un polinomio binario

In [4]:
def sumagal(a,b):  #suma de polinomios binarios, el grado de a es mayor o igual al de b
    gr1= len(a)-1
    gr2= len(b)-1
    s=np.zeros(gr1+1)
    for k in range(gr2+1):
        s[gr1-k]= (a[gr1- k]+b[gr2-k])%2 
    for k in range(gr2+1, gr1+1) :
        s[gr1-k]= a[gr1-k] %2
    return list(s)

In [151]:
a=[1,1,1,1,1]
b=[1,0,1]
list(sumapol(a,b))

[1.0, 1.0, 0.0, 1.0, 0.0]

[1, 1, 1, 1, 1]

In [118]:
a

[1, 1, 0, 1, 0]

In [25]:
if gr1==min(gr1,gr2):  # por si acaso
        for k in range(gr1+1,grs+1):
            s[grs-k] = a[gr1-k] %2
        return s    
    if gr2==min(gr1,gr2):
        for k in range(gr1+1,grs+1):
            s[grs-k] = a[gr1-k] %2
        return s

IndentationError: unindent does not match any outer indentation level (<ipython-input-25-3efa25660ac9>, line 5)

In [14]:
def divpol(p,i): # division de pol (todo binario) grp es mayor que gri
    grp = len(p)-1
    gri = len(i)-1
    difgrad = grp-gri
    dvd = p
    res=0
    while difgrad >= 0 :
        un=np.zeros(difgrad +1)
        un[0]=1
        res= sumagal(dvd, multpol(i,un)) 
        while res[0]==0 :
            del res[0]
        dvd = res
        difgrad = len(dvd)-1 -gri
    return res    

In [8]:
def multgal(a,b,i):  #multiplicacion de galois, todo binario
    c=divpol(multpol(a,b),i)
    return(c)

In [10]:
a=[1,0,1,0,1,1,1]
b=[1,0,0,0,0,0,1,1]

In [13]:
multgal(a,b,irr)

[1.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0]

In [ ]:
def eea(p,q,i):
    s0=1
    s1=0
    t0=0
    t1=1
    i=1
    r0=p
    r1=q
    r=divpol(r0,r1)
    while r!= 0 :
        r1= 



In [132]:
un=np.zeros(6)

In [133]:
un[0]=1

In [134]:
res= sumapol(p,multpol(irr,un))

In [135]:
res

array([ 0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  1.,  0.,  0.,  1.])

In [126]:
p= [1,0,1,0,1,1,0,1,1,1,1,0,0,1]

In [138]:
p[3:]

[0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1]

In [139]:
a=[0,1,2,3,4,5]

In [140]:
del a[0]

In [141]:
a

[1, 2, 3, 4, 5]

In [143]:
p

[1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1]

In [145]:
res

array([ 0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  1.,  0.,  0.,  1.])

In [147]:
del list(res)[0]

In [148]:
res

array([ 0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  1.,  0.,  0.,  1.])

In [9]:
irr=[1,0,0,0,1,1,0,1,1]

In [153]:
modirr(p,irr)

3
-1


[1.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0]

In [35]:
difgrad

NameError: name 'difgrad' is not defined

array([ 0.,  0.,  0.])

[2, 3, 2, 3, 2, 3, 2, 3]

In [46]:
sumapol(a,b)

IndexError: list index out of range

In [41]:
a

[1, 0, 1]

In [42]:
b

[1, 0, 1]

array([ 1.,  0.,  0.,  0.,  1.])

In [35]:
len('asdf')

4

In [38]:
[2,3] + [3,4]

[2, 3, 3, 4]

In [27]:
11%2

1

In [6]:
a=[1,1,1,1]
b=[2,4,6]
print(multpol(a,b))

[  8.  12.  12.   6.   4.]


In [18]:
a=[5,3]
b=[8,-2,5]
print(multpol(a,b))

[ 40.  14.  19.  15.]


In [19]:
a=[6,1]
b=[2,-5,3]
print(multpol(a,b))

[ 12. -28.  13.   3.]


In [11]:
len(multpol(a,b))

3

NameError: name 'c' is not defined

In [3]:
range(5)

range(0, 5)