In [1]:
import numpy as np

In [54]:
def multpol(a,b):  #multiplicacion de polinomios binarios
    gr1= len(a)-1  #el exponente decrece con la posicion
    gr2= len(b)-1  
    c=ceros(gr1+gr2+1)
    for k in range(0,gr1+gr2+1):
        for i in range (0,gr1+1):
            for j in range(0,gr2+1):
                if i+j == k : 
                    c[gr1+gr2-k] += a[gr1 -i] * b[gr2-j]
                    break
        c[gr1+gr2-k] =  c[gr1+gr2-k] %2           
    c = list (c)    
    while c[0]==0:
        del c[0]
        if c==[]:
            c=[0]
            break
    return c #se obtiene un polinomio binario

In [55]:
def sumagal(a,b):  #suma de polinomios binarios, el grado de a es mayor o igual al de b
    gr1= len(a)-1
    gr2= len(b)-1
    s=ceros(gr1+1)
    for k in range(gr2+1):
        s[gr1-k]= (a[gr1- k]+b[gr2-k])%2 
    for k in range(gr2+1, gr1+1) :
        s[gr1-k]= a[gr1-k] %2
    s = list (s)    
    while s[0]==0:
        del s[0]
        if s==[]:
            s=[0]
            break    
    return s

In [49]:
def ceros(n):
    l=[]
    for i in range(1,n+1):
        l=l+[0]
    return(l)    

In [57]:
def divpol(p,i): # division de pol (todo binario) grp es mayor que gri
    grp = len(p)-1
    gri = len(i)-1
    difgrad = grp-gri
    dvd = p
    res=0
    if gri > grp: 
        q=[0]
        res=p
    else : 
        q=ceros(grp-gri+1)
        while difgrad >= 0 :
            if i==[1] :
                q=p
                res=[0]
                break
            un=ceros(difgrad +1)
            un[0]=1
            q[grp-gri-difgrad]=1
            res= sumagal(dvd, multpol(i,un)) 
            dvd = res
            difgrad = len(dvd)-1 -gri
            if difgrad < 0 :
                break       
    return q,res    

In [29]:
len(np.array([1]))

1

In [28]:
abs(1-1.000001)

9.999999999177334e-07

In [10]:
def multgal(a,b,i):  #multiplicacion de galois, todo binario
    c=divpol(multpol(a,b),i)[1]
    return(c)

In [13]:
multgal(a,b,irr)

[1.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0]

In [14]:
divpol(p1,p2)

(array([ 1.]), [])

In [39]:
def eea(p,q):
    s0,s1= [1],[0]
    t0,t1= [0],[1]
    r0,r1= p,q
    r=[1]
    i=2
    while True :
        print(i)
        r=divpol(r0,r1)[1]
        print(r)
        if r==[0] :
            break
        q=divpol(sumagal(r0,r),r1)[0]
        print("r_i vale ", r)
        print("q_i vale ", q)
        s=sumagal(multpol(q,s1),s0)
        t=sumagal(multpol(q,t1),t0)
        print("t_i vale ",t)
        s0,s1=s1,s
        t0,t1=t1,t
        r0,r1=r1,r
        print(s0,s1,t0,t1,r0,r1)
        i+=1
    mcd=r1
    return [mcd,s,t]

In [40]:
def invgal(p,i):
    return eea(i,p)[2]

In [13]:
i=[1,0,0,0,1,1,0,1,1]

In [14]:
p=[1,1,0,0,0,0,1,0]

In [58]:
invgal(p,i)

2
[1, 0, 1, 1, 1, 0, 1]
r_i vale  [1, 0, 1, 1, 1, 0, 1]
q_i vale  [1, 1]
t_i vale  [1, 1]
[0] [1] [1] [1, 1] [1, 1, 0, 0, 0, 0, 1, 0] [1, 0, 1, 1, 1, 0, 1]
3
[1, 0, 0, 1, 0, 1]
r_i vale  [1, 0, 0, 1, 0, 1]
q_i vale  [1, 1]
t_i vale  [1, 0, 0]
[1] [1, 1] [1, 1] [1, 0, 0] [1, 0, 1, 1, 1, 0, 1] [1, 0, 0, 1, 0, 1]
4
[1, 0, 1, 1, 1]
r_i vale  [1, 0, 1, 1, 1]
q_i vale  [1, 0]
t_i vale  [1, 0, 1, 1]
[1, 1] [1, 1, 1] [1, 0, 0] [1, 0, 1, 1] [1, 0, 0, 1, 0, 1] [1, 0, 1, 1, 1]
5
[1, 0, 1, 1]
r_i vale  [1, 0, 1, 1]
q_i vale  [1, 0]
t_i vale  [1, 0, 0, 1, 0]
[1, 1, 1] [1, 1, 0, 1] [1, 0, 1, 1] [1, 0, 0, 1, 0] [1, 0, 1, 1, 1] [1, 0, 1, 1]
6
[1]
r_i vale  [1]
q_i vale  [1, 0]
t_i vale  [1, 0, 1, 1, 1, 1]
[1, 1, 0, 1] [1, 1, 1, 0, 1] [1, 0, 0, 1, 0] [1, 0, 1, 1, 1, 1] [1, 0, 1, 1] [1]
7
[0]


[1, 0, 1, 1, 1, 1]

In [59]:
p2=[1,0,0,0,1]

In [60]:
invgal(p2,i)

2
[1, 0, 1, 1]
r_i vale  [1, 0, 1, 1]
q_i vale  [1, 0, 0, 0, 0]
t_i vale  [1, 0, 0, 0, 0]
[0] [1] [1] [1, 0, 0, 0, 0] [1, 0, 0, 0, 1] [1, 0, 1, 1]
3
[1, 1, 1]
r_i vale  [1, 1, 1]
q_i vale  [1, 0]
t_i vale  [1, 0, 0, 0, 0, 1]
[1] [1, 0] [1, 0, 0, 0, 0] [1, 0, 0, 0, 0, 1] [1, 0, 1, 1] [1, 1, 1]
4
[1, 0]
r_i vale  [1, 0]
q_i vale  [1, 1]
t_i vale  [1, 1, 1, 0, 0, 1, 1]
[1, 0] [1, 1, 1] [1, 0, 0, 0, 0, 1] [1, 1, 1, 0, 0, 1, 1] [1, 1, 1] [1, 0]
5
[1]
r_i vale  [1]
q_i vale  [1, 1]
t_i vale  [1, 0, 1, 1, 0, 1, 0, 0]
[1, 1, 1] [1, 0, 1, 1] [1, 1, 1, 0, 0, 1, 1] [1, 0, 1, 1, 0, 1, 0, 0] [1, 0] [1]
6
[0]


[1, 0, 1, 1, 0, 1, 0, 0]

In [61]:
p3=[1,1,1,1,0,0,0]

In [62]:
invgal(p3,i)

2
[1, 0, 1, 1]
r_i vale  [1, 0, 1, 1]
q_i vale  [1, 1, 0]
t_i vale  [1, 1, 0]
[0] [1] [1] [1, 1, 0] [1, 1, 1, 1, 0, 0, 0] [1, 0, 1, 1]
3
[1, 1, 1]
r_i vale  [1, 1, 1]
q_i vale  [1, 1, 0, 1]
t_i vale  [1, 0, 1, 1, 1, 1]
[1] [1, 1, 0, 1] [1, 1, 0] [1, 0, 1, 1, 1, 1] [1, 0, 1, 1] [1, 1, 1]
4
[1, 0]
r_i vale  [1, 0]
q_i vale  [1, 1]
t_i vale  [1, 1, 1, 0, 1, 1, 1]
[1, 1, 0, 1] [1, 0, 1, 1, 0] [1, 0, 1, 1, 1, 1] [1, 1, 1, 0, 1, 1, 1] [1, 1, 1] [1, 0]
5
[1]
r_i vale  [1]
q_i vale  [1, 1]
t_i vale  [1, 0, 1, 1, 0, 1, 1, 0]
[1, 0, 1, 1, 0] [1, 1, 0, 1, 1, 1] [1, 1, 1, 0, 1, 1, 1] [1, 0, 1, 1, 0, 1, 1, 0] [1, 0] [1]
6
[0]


[1, 0, 1, 1, 0, 1, 1, 0]

In [51]:
ceros(2)

[0, 0]

In [17]:
p=[1,0,1,1]
a=[1,0,0]

In [29]:
divpol(p,a)[1]

[1.0, 1.0]

In [31]:
divpol(sumagal(p,[1,1]),a)[0]

array([ 1.,  0.])

In [28]:
sumagal([1,0],p)

[0.0, 0.0]

In [41]:
eea(p,a)

1


ValueError: negative dimensions are not allowed

In [1]:
p1,p2=[1,1],[1,1]

In [132]:
un=np.zeros(6)

In [133]:
un[0]=1

In [134]:
res= sumapol(p,multpol(irr,un))

In [135]:
res

array([ 0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  1.,  0.,  0.,  1.])

In [126]:
p= [1,0,1,0,1,1,0,1,1,1,1,0,0,1]

In [138]:
p[3:]

[0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1]

In [139]:
a=[0,1,2,3,4,5]

In [140]:
del a[0]

In [141]:
a

[1, 2, 3, 4, 5]

In [143]:
p

[1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1]

In [145]:
res

array([ 0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  1.,  0.,  0.,  1.])

In [147]:
del list(res)[0]

In [148]:
res

array([ 0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  1.,  0.,  0.,  1.])

In [9]:
irr=[1,0,0,0,1,1,0,1,1]

In [153]:
modirr(p,irr)

3
-1


[1.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0]

In [35]:
difgrad

NameError: name 'difgrad' is not defined

array([ 0.,  0.,  0.])

[2, 3, 2, 3, 2, 3, 2, 3]

In [46]:
sumapol(a,b)

IndexError: list index out of range

In [41]:
a

[1, 0, 1]

In [42]:
b

[1, 0, 1]

array([ 1.,  0.,  0.,  0.,  1.])

In [35]:
len('asdf')

4

In [38]:
[2,3] + [3,4]

[2, 3, 3, 4]

In [27]:
11%2

1

In [6]:
a=[1,1,1,1]
b=[2,4,6]
print(multpol(a,b))

[  8.  12.  12.   6.   4.]


In [18]:
a=[5,3]
b=[8,-2,5]
print(multpol(a,b))

[ 40.  14.  19.  15.]


In [19]:
a=[6,1]
b=[2,-5,3]
print(multpol(a,b))

[ 12. -28.  13.   3.]


In [11]:
len(multpol(a,b))

3

NameError: name 'c' is not defined

In [3]:
range(5)

range(0, 5)